-- cricketteam.sql
-- SQL script to create a cricket team database with 50+ players

CREATE TABLE cricket_team (
    player_id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    jerseynumber INTEGER NOT NULL,
    role TEXT NOT NULL,
    country TEXT NOT NULL,
    team TEXT NOT NULL,
    total_century INTEGER DEFAULT 0,
    wickets INTEGER DEFAULT 0
);

-- Sample data for 50+ players
INSERT INTO cricket_team (name, jerseynumber, role, country, team, total_century, wickets) VALUES
('Virat Kohli', 18, 'Batsman', 'India', 'India', 77, 0),
('Rohit Sharma', 45, 'Batsman', 'India', 'India', 45, 0),
('Jasprit Bumrah', 93, 'Bowler', 'India', 'India', 0, 150),
('Ravindra Jadeja', 8, 'All-rounder', 'India', 'India', 3, 220),
('Rishabh Pant', 17, 'Wicket-keeper', 'India', 'India', 6, 0),
('Babar Azam', 56, 'Batsman', 'Pakistan', 'Pakistan', 30, 0),
('Shaheen Afridi', 10, 'Bowler', 'Pakistan', 'Pakistan', 0, 120),
('Mohammad Rizwan', 16, 'Wicket-keeper', 'Pakistan', 'Pakistan', 8, 0),
('Fakhar Zaman', 39, 'Batsman', 'Pakistan', 'Pakistan', 12, 0),
('Shadab Khan', 7, 'All-rounder', 'Pakistan', 'Pakistan', 2, 90),
('Steve Smith', 49, 'Batsman', 'Australia', 'Australia', 44, 0),
('David Warner', 31, 'Batsman', 'Australia', 'Australia', 43, 0),
('Pat Cummins', 30, 'Bowler', 'Australia', 'Australia', 0, 180),
('Glenn Maxwell', 32, 'All-rounder', 'Australia', 'Australia', 8, 60),
('Alex Carey', 4, 'Wicket-keeper', 'Australia', 'Australia', 3, 0),
('Kane Williamson', 22, 'Batsman', 'New Zealand', 'New Zealand', 28, 0),
('Trent Boult', 18, 'Bowler', 'New Zealand', 'New Zealand', 0, 170),
('Tom Latham', 48, 'Wicket-keeper', 'New Zealand', 'New Zealand', 7, 0),
('Martin Guptill', 31, 'Batsman', 'New Zealand', 'New Zealand', 16, 0),
('James Neesham', 50, 'All-rounder', 'New Zealand', 'New Zealand', 2, 70),
('Joe Root', 66, 'Batsman', 'England', 'England', 36, 0),
('Ben Stokes', 55, 'All-rounder', 'England', 'England', 11, 100),
('Jos Buttler', 63, 'Wicket-keeper', 'England', 'England', 10, 0),
('Jofra Archer', 22, 'Bowler', 'England', 'England', 0, 80),
('Jonny Bairstow', 51, 'Batsman', 'England', 'England', 15, 0),
('Chris Gayle', 45, 'Batsman', 'West Indies', 'West Indies', 42, 0),
('Jason Holder', 98, 'All-rounder', 'West Indies', 'West Indies', 3, 120),
('Nicholas Pooran', 29, 'Wicket-keeper', 'West Indies', 'West Indies', 5, 0),
('Kemar Roach', 24, 'Bowler', 'West Indies', 'West Indies', 0, 110),
('Shimron Hetmyer', 2, 'Batsman', 'West Indies', 'West Indies', 4, 0),
('Quinton de Kock', 12, 'Wicket-keeper', 'South Africa', 'South Africa', 18, 0),
('Kagiso Rabada', 25, 'Bowler', 'South Africa', 'South Africa', 0, 140),
('Faf du Plessis', 18, 'Batsman', 'South Africa', 'South Africa', 23, 0),
('David Miller', 10, 'Batsman', 'South Africa', 'South Africa', 9, 0),
('Andile Phehlukwayo', 5, 'All-rounder', 'South Africa', 'South Africa', 1, 60),
('Shakib Al Hasan', 75, 'All-rounder', 'Bangladesh', 'Bangladesh', 9, 130),
('Tamim Iqbal', 28, 'Batsman', 'Bangladesh', 'Bangladesh', 14, 0),
('Mushfiqur Rahim', 15, 'Wicket-keeper', 'Bangladesh', 'Bangladesh', 8, 0),
('Mustafizur Rahman', 90, 'Bowler', 'Bangladesh', 'Bangladesh', 0, 100),
('Mahmudullah', 30, 'All-rounder', 'Bangladesh', 'Bangladesh', 3, 50),
('Dimuth Karunaratne', 15, 'Batsman', 'Sri Lanka', 'Sri Lanka', 7, 0),
('Lasith Malinga', 99, 'Bowler', 'Sri Lanka', 'Sri Lanka', 0, 338),
('Kusal Perera', 16, 'Wicket-keeper', 'Sri Lanka', 'Sri Lanka', 6, 0),
('Angelo Mathews', 69, 'All-rounder', 'Sri Lanka', 'Sri Lanka', 5, 120),
('Dhananjaya de Silva', 74, 'All-rounder', 'Sri Lanka', 'Sri Lanka', 2, 40),
('Paul Stirling', 1, 'Batsman', 'Ireland', 'Ireland', 13, 0),
('Kevin O Brien', 82, 'All-rounder', 'Ireland', 'Ireland', 4, 60),
('Lorcan Tucker', 4, 'Wicket-keeper', 'Ireland', 'Ireland', 2, 0),
('Mark Adair', 32, 'Bowler', 'Ireland', 'Ireland', 0, 50),
('Andy Balbirnie', 63, 'Batsman', 'Ireland', 'Ireland', 7, 0),
('Rashid Khan', 19, 'Bowler', 'Afghanistan', 'Afghanistan', 1, 150),
('Mohammad Nabi', 7, 'All-rounder', 'Afghanistan', 'Afghanistan', 3, 120),
('Rahmanullah Gurbaz', 21, 'Wicket-keeper', 'Afghanistan', 'Afghanistan', 2, 0),
('Hashmatullah Shahidi', 50, 'Batsman', 'Afghanistan', 'Afghanistan', 4, 0);
